### ISSUE TITLE
Upgrade broke the site

### ISSUE THREAD

**Issue by hzm170** [YunoHost-Apps/sharkey_ynh#52]
here the error 

`025-06-01 00:01:45,313: DEBUG - packages/frontend build: error during build:
2025-06-01 00:01:45,314: DEBUG - packages/frontend build: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'minimatch' imported from /var/www/sharkey/packages/frontend/node_modules/.vite-temp/vite.config.ts.timestamp-1748736105135-4ca99c2c9c0d7.mjs
2025-06-01 00:01:45,314: DEBUG - packages/frontend build: Did you mean to import "minimatch/dist/commonjs/index.js"?
2025-06-01 00:01:45,314: DEBUG - packages/frontend build:     at Object.getPackageJSONURL (node:internal/modules/package_json_reader:256:9)
2025-06-01 00:01:45,314: DEBUG - packages/frontend build:     at packageResolve (node:internal/modules/esm/resolve:768:81)
2025-06-01 00:01:45,314: DEBUG - packages/frontend build:     at moduleResolve (node:internal/modules/esm/resolve:854:18)
2025-06-01 00:01:45,314: DEBUG - packages/frontend build:     at defaultResolve (node:internal/modules/esm/resolve:984:11)
2025-06-01 00:01:45,314: DEBUG - packages/frontend build:     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
2025-06-01 00:01:45,315: DEBUG - packages/frontend build:     at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
2025-06-01 00:01:45,315: DEBUG - packages/frontend build:     at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
2025-06-01 00:01:45,315: DEBUG - packages/frontend build:     at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
2025-06-01 00:01:45,315: DEBUG - packages/frontend build:     at ModuleJob._link (node:internal/modules/esm/module_job:137:49)
2025-06-01 00:01:45,421: DEBUG - packages/frontend build: Failed
2025-06-01 00:01:45,423: DEBUG - /var/www/sharkey/packages/frontend:
2025-06-01 00:01:45,423: DEBUG -  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  frontend@ build: `vite build`
2025-06-01 00:01:45,423: DEBUG - Exit status 1
2025-06-01 00:01:45,722: DEBUG -  ELIFECYCLE  Command failed with exit code 1.
2025-06-01 00:01:45,812: DEBUG - + ynh_exit_properly
2025-06-01 00:01:45,817: DEBUG - + [[ install =~ ^install$|^upgrade$|^restore$ ]]
2025-06-01 00:01:46,436: ERROR - Unable to install sharkey: An error occurred inside the app installation script`

not sure if any one else getting this error yet..?

if there a fix let me know

**Comment by KodeIn** [comment]
I had a similar issue weeks ago : https://github.com/YunoHost-Apps/sharkey_ynh/issues/48

From what [kevadesu](https://github.com/kevadesu) answered to my issue : it seems the backup via yunohost doesn't include sharkey users tables. But some traces of the users remain, preventing from recreating them.

**Comment by kevadesu** [comment]
I have actually found out that YunoHost has the database inside of the backup file itself, but just doesn't know how to restore it, so I'll just write up a quick guide on how to do it

**Comment by kevadesu** [comment]
Since I didn't find an easy way to explain it, [here's a guide I wrote](https://rootsource.cc/Articles/restoresharkeyynh/)

**Comment by hzm170** [comment]
that if it was installed i had to wipe my server out due to issues i had but now the app just does not want to install as above post i made..

**Comment by kevadesu** [comment]
> that if it was installed i had to wipe my server out due to issues i had but now the app just does not want to install as above post i made..

is that from restoring the backup or just from trying to clean install?

**Comment by KodeIn** [comment]
Last time I tried to update, it looks like there are broken parts in the megalodon package preventing from installing the update.
https://paste.yunohost.org/raw/soqibecodu

 Then yunohost try to rollback to backup and since the database restoration is broken, we end up with a broken sharkey until the db is restored by hand.

**Comment by tr1p0p** [comment]
I cannot understand how to restore a backup that yunohost cannot restore when i follow the kevadesu guide. And i try restoring the db on a clean install, but no success in this side either ( https://paste.yunohost.org/raw/sowejohove ).

So i don't find anyway to restore sharkey. Do i have to edit the script inside the archive backup ?

**Comment by KodeIn** [comment]
> I cannot understand how to restore a backup that yunohost cannot restore when i follow the kevadesu guide. And i try restoring the db on a clean install, but no success in this side either ( https://paste.yunohost.org/raw/sowejohove ).
> 
> So i don't find anyway to restore sharkey. Do i have to edit the script inside the archive backup ?

My backup could restore, the only problem was with the DB, so I just had to repopulate it using kevadesu guide.
I don't know how to fix a backup that doesn't restore, sorry.

EDIT :
Looks like you're hit with the recent NodeJS & PNPM version disappearance that impact quite a bunch of yunohost apps. Can't really help you on how to fix that. Maybe there is a file somewhere to specify the version to use in the backup tar, but I don't know which or where to find it.
EDIT²:
From what I remember trying, I copied the NodeJS version it wanted from `/usr/local/n/versions/node/` to `/opt/node_n/n/versions/node/`, then restored the backup, then "fixed" nodejs in `sharkey.service` and restored sql.db.

**Comment by tr1p0p** [comment]
> My backup could restore, the only problem was with the DB, so I just had to repopulate it using kevadesu guide. I don't know how to fix a backup that doesn't restore, sorry.
> 
> EDIT : Looks like you're hit with the recent NodeJS & PNPM version disappearance that impact quite a bunch of yunohost apps. Can't really help you on how to fix that. Maybe there is a file somewhere to specify the version to use in the backup tar, but I don't know which or where to find it. EDIT²: From what I remember trying, I copied the NodeJS version it wanted from `/usr/local/n/versions/node/` to `/opt/node_n/n/versions/node/`, then restored the backup, then "fixed" nodejs in `sharkey.service` and restored sql.db.

Yeah i try to edit the script and some stuffs into the tar archives to try to fix that **but** yunohost said it's a invalid .json then, because the date/size checksum not match now. And i don't know the way to have the particular checksum of the .json of the yunohost backup.

**Comment by KodeIn** [comment]
I'm far too late to answer but I'll leave here the method people recommended on other yunoapp's github to fix troubles with PNPM during restoration  :
- first check which PNPM version is available in `/opt/node_n/n/versions/node/`
- go to your backup folder, copy the sharkey backup, extract sharkey.service from it and edit the two lines in the file referring to PNPM (use your favourite text editor, I use nano)
```
cp sharkey-pre-update1.tar sharkey-copy.tar
tar -xvf sharkey-copy.tar apps/sharkey/backup/etc/systemd/system/sharkey.service
nano apps/sharkey/backup/etc/systemd/system/sharkey.service
```
- update the .tar with the edited file
`tar --update -f sharkey-copy.tar apps/sharkey/backup/etc/systemd/system/sharkey.service`
- launch yunohost restoration
`yunohost backup restore sharkey-copy.tar --apps`

It should fix the PNPM trouble. At least it did for me.

**Comment by looowizz** [comment]
Hello!

Just going to repeat the comment I made in a [similar issue](https://github.com/YunoHost-Apps/sharkey_ynh/issues/58) here for visibility

After hearing about an [upcoming security update](https://sharkey.team/notes/ajka8rybkjf80061), I thought I'd try and do something about this. I have made a fork of this repo and simply reverted the install/upgrade code to what it was originally before what changes I think caused issues. 

I haven't tested it fully on my instance, however running the same steps manually, rather than through YunoHost, did end up solving my issues and my instance is now on 2025.4.5 (the latest version).

To upgrade using my fork, run `sudo yunohost app upgrade sharkey -u https://github.com/looowizz/sharkey_ynh`. Let me know how it goes and I might consider making a pull request.

If you do have any issues, I am happy to help :)

**Comment by tr1p0p** [comment]
So.. .Still an issue hun ? Don't understand what's missing for the dev of this package to make it work, but guess it's like that...
